---
- name: install node and npm
  hosts: webservers
  tasks:
    - name: update apt cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    - name: install node & npm
      apt:
        pkg:
         - nodejs
         - npm

- name: create user for deploying and running node app
  hosts: webservers
  tasks:
    - name: create linux user
      user:
        name: tanner-nodejs
        comment: Tanner
        group: admin
      register: user_creation_results
    - debug: msg={{user_creation_results}}


- name: Deploy nodejs app
  hosts: webservers
  become: True
  become_user: tanner-nodejs
  vars:
    - destination: /home/tanner-nodejs
  tasks:
    - name: unpack file
      unarchive:
        src: "{{ location }}/nodejs-app-{{version}}.tgz"
        dest: "{{ destination }}"
      register: unpack_results
    - debug: msg={{unpack_results}}
    - name: install dependencies
      npm:
        path: "{{destination/package}}"
    - name: start the app
      chdir: "{{destination}}/package/app"
      command: node server
      async: 1000
      poll: 0
    - name: Ensure app is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status.stdout_lines}}

